https://psychic-space-trout-r7676rqpgxr93xw69-5109.app.github.dev = https://github.dev

GET {{host}}/api/students
###

GET {{host}}/api/students/1
###

POST {{host}}/api/students
Content-Type: application/json

{
  "name": "Мария",
  "course": 1
}
###

PUT {{host}}/api/students/1
Content-Type: application/json

{
  "name": "Анна Петрова",
  "course": 3
}
###

DELETE {{host}}/api/students/2
###

POST {{host}}/api/students
Content-Type: application/json

{
  "name": "",
  "course": 7
}
